/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'ams_db',
  tableName: 'content_detail',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'content_id',
      isInteger: true,
      required: true
    },
    v3id: {
      model: 'LessonData',
      columnName: 'v3id'
    },
    createdAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'create_time',
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'update_time',
      autoUpdatedAt: true
    },
    content_title: {
      type: 'string',
      allowNull: true
    },
    channel_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    content_introduction: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    publish_time: {
      type: "ref",
      columnType: "timestamp",
      defaultsTo: "0000-00-00 00:00:00"
    },
    grammar_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    content_image: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    audio_dialogue: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    audio_public: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    ppt: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    production_id: {
      type: 'number',
      allowNull: true
    },
    function_ids: {
      type: 'string',
      allowNull: true
    },
    hash_code: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    from: {
      type: 'string',
      allowNull: true
    },
    mp3_url: {
      type: 'string',
      allowNull: true
    },
    um_id: {
      type: 'number',
      allowNull: true
    }
  }
};
