/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'api_clients',
  attributes: {
    id: {
      type: "string",
      columnType: "varchar",
      columnName: 'client_id',
      maxLength: 100,
      required: true
    },
    client_secret: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      required: true
    },
    createdAt: {
      type: "ref",
      columnType: "datetime",
      columnName: "date",
      required: true
    },
    client_version: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    client_timeout: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    updatedAt: false
  }
};
