/**
 Generated by sails-inverse-model
 Date:Mon Sep 30 2019 12:48:33 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'assessment',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    name: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    v3_id: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    product_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      allowNull: true
    },
    level_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    random: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    counter: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    min_num: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    max_num: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    intro: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    creator_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    createdAt: {
      type: "string",
      columnName: 'created_at',
      columnType: "datetime",
      autoCreatedAt: true
    },
    updatedAt: {
      type: "string",
      columnName: 'updated_at',
      columnType: "datetime",
      autoUpdatedAt: true
    },
    status: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    }
  }
};
