/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  customToJSON: function() {
    // Return a shallow copy of this record with the password and ssn removed.
    return _.pick(this, ['id', 'content', 'user', 'reply_to_id', 'reply_to_id_2', 'reply_to_user_id',
      'comment_from', 'nestedComments', 'reply_count', 'createdAt'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    parent_id: {
      model: 'LessonData'
    },
    content: {
      type: "string",
      columnType: "text"
    },
    published: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    user: {
      model: 'User',
      columnName: 'user_id',
      required: true
    },
    type: {
      type: "string",
      columnType: "enum",
      isIn: ["lesson", "post", "grammar", "dictionary", "group"],
      required: true
    },
    reply_to_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    reply_to_id_2: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    reply_to_user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    comment_from: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    device: {
      type: "string",
      columnType: "char",
      maxLength: 12,
      defaultsTo: "web"
    },
    reply_count: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    group_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    createdAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'created_at',
      defaultsTo: "CURRENT_TIMESTAMP"
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'updated_at',
      defaultsTo: "0000-00-00 00:00:00"
    },
  }
};
