/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true,
      autoIncrement: true
    },
    lessonId: {
      columnName: "v3_id",
      model: 'LessonData'
    },
    user_id: {
      model: 'User'
    },
    rate: {
      type: 'number',
      isInteger: true,
      required: true
    },
    createdAt:{
      type: 'ref',
      autoCreatedAt: true
    },
    updatedAt:{
      type: 'ref',
      autoUpdatedAt: true
    }
  }
};
