/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'content_grammar_tag',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    v3_id: {
      type: "string",
      columnType: "varchar",
      maxLength: 20,
      required: true
    },
    grammar_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    url: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      required: true
    },
    createdAt: {
      type: "ref",
      columnName:'create_time',
      columnType: "datetime",
    },
    updatedAt: false
  }
};
