/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'content_expansions',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    v3_id: {
      model: 'LessonData'
    },
    display_order: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    vocabulary: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    row_1: {
      type: "string",
      columnType: "mediumtext",
      required: true
    },
    row_2: {
      type: "string",
      columnType: "text",
      required: true
    },
    row_3: {
      type: "string",
      columnType: "text",
      required: true
    },
    row_4: {
      type: "string",
      columnType: "text",
      required: true
    },
    audio: {
      type: "string",
      columnType: "text",
      required: true
    },
    updatedAt: false,
    createdAt: false
  }
};
