/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'course_detail',
  customToJSON: function() {
    // Return a shallow copy of this record with the password and ssn removed.
    return _.pick(this, ['id', 'course_title', 'course_introduction', 'course_image', 'hash_code']);
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'course_id',
      isInteger: true,
      required: true
    },
    ams_course_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    course_title: {
      type: "string",
      columnType: "varchar",
      maxLength: 255
    },
    channel_id: {
      type: "number",
      columnType: "int",
      isInteger: true
    },
    type: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    course_introduction: {
      type: "string",
      columnType: "text"
    },
    course_hightlight: {
      type: "string",
      columnType: "text",
      required: true
    },
    publish_time: {
      type: "ref",
      columnType: "datetime"
    },
    course_image: {
      type: "string",
      columnType: "varchar",
      maxLength: 255
    },
    level_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    createdAt: {
      type: "ref",
      columnType: "datetime",
      columnName: 'create_time',
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'update_time',
      autoUpdatedAt: true
    },
    created_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    updated_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    is_private: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    pubstatus: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    course_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    hash_code: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    org_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 1
    },
    closed: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    order_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    publish_from: {
      type: "string",
      columnType: "date",
      required: true
    },
    publish_to: {
      type: "string",
      columnType: "date",
      required: true
    }
  }
};
