/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'course_contents',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'course_content_id',
      isInteger: true,
      autoIncrement: true
    },
    course_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    lesson: {
      model: 'LessonData',
      columnName: 'v3_id'
    },
    displaysort: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    cratedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'create_time',
      defaultsTo: "CURRENT_TIMESTAMP"
    },
    updatedAt: false
  }
};
