/**
 Generated by sails-inverse-model
 Date:Thu Aug 29 2019 10:33:08 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'game_logs',
  datastore: 'logging',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    app: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    user: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    identifier: {
      type: "string",
      columnType: "varchar",
      maxLength: 265,
      allowNull: true
    },
    game_type: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      defaultsTo: "charCrush"
    },
    game_length: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    time_ended: {
      type: "string",
      columnType: "datetime",
      defaultsTo: "CURRENT_TIMESTAMP"
    },
    longest_streak: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    characters_not_used: {
      type: "string",
      columnType: "text"
    },
    characters_used: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    points: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    isTraditional: {
      type: 'number',
      columnType: 'int',
      columnName: 'is_traditional',
      isInteger: true,
      defaultsTo: 0
    },
    createdAt: {
      type: "string",
      columnType: "timestamp",
      columnName: 'created_at',
      autoCreatedAt: true
    },
    updatedAt: false
  }
};
