/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'gift_tracking',
  attributes: {
    id: {
      columnName: 'user_id',
      type: 'number',
      required: true
    },
    transaction_id: {
      model: 'Transactions'
    },
    address: {
      type: 'string'
    },
    sentDate: {
      type: "string",
      columnType: "datetime",
      required: true
    },
    updatedAt: {
      type: "string",
      columnType: "datetime",
      defaultsTo: "CURRENT_TIMESTAMP"
    },
    createdAt: false
  }
};
