/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'grammar_block',
  customToJSON: function() {
    return _.pick(this, ['grammar', 'examples', 'updatedAt'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'grammar_block_id',
      isInteger: true,
      required: true
    },
    description: {
      type: "string",
      columnType: "varchar",
      maxLength: 1000
    },
    summary: {
      type: "string",
      columnType: "varchar",
      maxLength: 1000,
      required: true
    },
    display_sort: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      required: true
    },
    examples: {
      collection: 'GrammarSentence',
      via: 'grammar_block_id'
    },
    grammar: {
      columnName: 'grammar_id',
      model: 'GrammarDetail'
    },
    createdAt: {
      type: "ref",
      columnName:'create_time',
      columnType: "datetime"
    },
    updatedAt: {
      type: "ref",
      columnName:'update_time',
      columnType: "datetime"
    }
  }
};
