/**
 Generated by sails-inverse-model
 Date:Fri Jul 19 2019 13:29:48 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'logging',
  tableName: 'cp_accesslog',
  attributes: {
    id: {
      type: "string",
      columnName: 'accesslog_user',
      required: true,
    },
    createdAt: {
      type: "string",
      columnType: "datetime",
      columnName: 'accesslog_time',
      autoCreatedAt: true
    },
    access_ip: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    accesslog_url: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    accesslog_sessionid: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    accesslog_urlbase: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    accesslog_locId: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    accesslog_country: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    referer: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    campaign_code: {
      type: "string",
      columnType: "varchar",
      allowNull: true
    },
    updatedAt: false,
  }
};
