/**
 Generated by sails-inverse-model
 Date:Fri Jul 19 2019 13:29:48 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'logging',
  tableName: 'mautic_error_logs',
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      autoIncrement: true
    },
    userId: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      allowNull: true
    },
    error: {
      type: 'string',
      columnType: 'text',
      allowNull: true
    },
    createdAt: {
      type: 'string',
      columnType: "datetime",
      autoCreatedAt: true
    },
    updatedAt: false
  }
};
