/**
 Generated by sails-inverse-model
 Date:Fri Jul 19 2019 13:29:48 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'mauticDb',
  tableName: 'ma_leads',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    owner_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    stage_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    is_published: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    createdAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'date_added'
    },
    created_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    created_by_user: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'date_modified',
      autoUpdatedAt: true
    },
    modified_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    modified_by_user: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    checked_out: {
      type: "string",
      columnType: "timestamp",
      allowNull: true
    },
    checked_out_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    checked_out_by_user: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    points: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    last_active: {
      type: "ref",
      columnType: "timestamp",
      allowNull: true
    },
    internal: {
      type: "string",
      columnType: "longtext",
      allowNull: true
    },
    social_cache: {
      type: "string",
      columnType: "longtext",
      allowNull: true
    },
    date_identified: {
      type: "ref",
      columnType: "timestamp"
    },
    preferred_profile_image: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    title: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    firstname: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    lastname: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    company: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    position: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    email: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    phone: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    mobile: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    address1: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    address2: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    city: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    state: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    zipcode: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    timezone: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    country: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    fax: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    preferred_locale: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    attribution_date: {
      type: "ref",
      columnType: "timestamp"
    },
    attribution: {
      type: "number",
      columnType: "double",
      allowNull: true
    },
    website: {
      type: "string",
      columnType: "longtext",
      allowNull: true
    },
    facebook: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    foursquare: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    googleplus: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    instagram: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    linkedin: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    skype: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    twitter: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    level: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    subscription: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    fullname: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    subscribedate: {
      type: "ref",
      columnType: "date"
    },
    promo: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      allowNull: true
    },
    academic: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      allowNull: true
    },
    userid: {
      type: "string",
      columnType: "tinytext",
      allowNull: true
    },
    expirydate: {
      type: "ref",
      columnType: "date"
    },
  }
};
