/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'ny_session',
  attributes: {
    id: {
      type: "string",
      columnType: "varchar",
      columnName: 'session_id',
      maxLength: 200,
      required: true,
      unique: true,
    },
    createAt: {
      type: "string",
      columnType: "datetime",
      columnName: 'start_session_date',
      autoCreatedAt: true
    },
    updatedAt: {
      type: "string",
      columnType: "datetime",
      columnName: 'last_access_date',
      autoUpdatedAt: true
    },
    session_language_code: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    email: {
      type: "string",
      columnType: "varchar",
      columnName: 'session_user_id',
      maxLength: 200,
      allowNull: true
    },
    session_folder_id: {
      type: "string",
      columnType: "varchar",
      maxLength: 60,
      allowNull: true
    },
    session_query_code: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    admin_session: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    param1: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    param2: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    param3: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    session_ip_address: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      allowNull: true
    },
    session_inactive: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    client_id: {
      type: "ref",
      columnType: "varchar",
      maxLength: 100,
    },
  }
};
