/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'sessions',
  attributes: {
    id: {
      type: "string",
      columnType: "varchar",
      maxLength: 32,
      required: true,
      columnName: 'session_id'
    },
    session_user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    session_start: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    session_time: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    session_data: {
      type: "string",
      columnType: "mediumtext",
      required: true,
    },
    updatedAt: false,
    createdAt: false
  }
};
