/**
 Generated by sails-inverse-model
 Date:Fri Jul 19 2019 13:29:48 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'chinesepod2015',
  tableName: 'Products',
  customToJSON: function() {
    // Return a shallow copy of this record with the password and ssn removed.
    return _.pick(this, ['product_title'])
  },
  attributes: {
    id: {
      type: "number",
      columnName: 'product_id',
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    product_type_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    subscription_type: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    product_length: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    product_title: {
      type: "string",
      columnType: "text"
    },
    createdAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'date_created'
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'last_modified',
      autoUpdatedAt: true
    },
  }
};
