/**
 Generated by sails-inverse-model
 Date:Fri Jul 19 2019 13:29:48 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'chinesepod2015',
  tableName: 'Promotions',
  attributes: {
    id: {
      type: "number",
      columnName: 'promotion_id',
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    product_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    channel_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    promotion_code: {
      type: 'string',
      columnType: 'varchar'
    },
    description: {
      type: 'string',
      columnType: 'tinytext',
      allowNull: true
    },
    type: {
      type: 'number',
      columnType: 'tinyint'
    },
    value: {
      type: 'ref',
      columnType: 'char'
    },
    max_uses: {
      type: 'number',
      columnType: 'smallint'
    },
    times_used: {
      type: 'number',
      columnType: 'smallint'
    },
    expiry_date: {
      type: "ref",
      columnType: "timestamp",
    },
    code_status: {
      type: 'number',
      columnType: "int",
      isInteger: true
    },
    createdAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'date_created'
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'last_modified',
      autoUpdatedAt: true
    },
    created_by: {
      type: 'number',
      columnType: 'int'
    },
    modified_by: {
      type: 'number',
      columnType: 'int'
    },
  }
};
