/**
 Generated by sails-inverse-model
 Date:Mon Sep 30 2019 12:48:33 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'assessment',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    title: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    title_2: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    title_3: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    options: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    options_2: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    options_3: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    answers: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    tip: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    scope: {
      type: "string",
      columnType: "varchar",
      maxLength: 1000
    },
    score: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      allowNull: true
    },
    type_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    category_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    level_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    product_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    creator_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    createdAt: {
      type: "ref",
      columnName: 'created_at',
      columnType: "datetime",
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnName: 'updated_at',
      columnType: "datetime",
      // autoUpdatedAt: true
    },
    status: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    }
  }
};
