/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'refresh_tokens',
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    createdAt: {
      type: "string",
      columnType: "datetime",
      autoCreatedAt: true
    },
    updatedAt: {
      type: "string",
      columnType: "datetime",
      autoUpdatedAt: true
    },
    expiry: {
      type: "string",
      columnType: "datetime",
      defaultsTo: new Date(Date.now() + 1000 * 60 * 60)
    },
    user_id: {
      model: 'User'
    },
    refresh_token: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    ip_address: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    user_agent: {
      type: 'string',
      columnType: 'text',
      allowNull: true
    },
    client_id: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
  }
};
