/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'transaction_addresses',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true
    },
    transaction_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    country: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      required: true
    },
    state: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      allowNull: true
    },
    city: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      required: true
    },
    zip_code: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      allowNull: true
    },
    phone: {
      type: "string",
      columnType: "varchar",
      maxLength: 50,
      allowNull: true
    },
    company_name: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      allowNull: true
    },
    full_name: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      required: true
    },
    address1: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      allowNull: true
    },
    address2: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      allowNull: true
    },
    updatedAt: {
      type: "ref",
      columnName: 'last_update',
      columnType: "timestamp",
      autoUpdatedAt: true
    }
  }
};
