/**
	Generated by sails-inverse-model
	Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        time: {
            type: "string",
            columnType: "timestamp",
            defaultsTo: "CURRENT_TIMESTAMP"
        },
        user_id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        user_email: {
            type: "string",
            columnType: "varchar",
            maxLength: 200,
            required: true
        },
        subscription_id: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        type: {
            type: "string",
            columnType: "varchar",
            maxLength: 10,
            required: true
        },
        txn_type: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        description: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        amount: {
            type: "number",
            columnType: "float",
            required: true
        },
        card_num: {
            type: "string",
            columnType: "varchar",
            maxLength: 30,
            required: true
        },
        exp_date: {
            type: "string",
            columnType: "varchar",
            maxLength: 30,
            required: true
        },
        cust_id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        first_name: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        last_name: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        email: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
            required: true
        },
        phone: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        company: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        country: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        address: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
            required: true
        },
        city: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        zip: {
            type: "string",
            columnType: "varchar",
            maxLength: 30,
            required: true
        },
        state: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        edited: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        },
        status: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        },
        gift: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        },
        approved: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        resp_code: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        resp_reason_code: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        resp_reason_text: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        response: {
            type: "string",
            columnType: "text",
            required: true
        },
        serialize: {
            type: "string",
            columnType: "text",
            required: true
        },
        text: {
            type: "string",
            columnType: "text",
            required: true
        },
        cron: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        }
    }
};