/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_settings',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true,
      autoIncrement: true
    },
    user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      unique: true,
      required: true
    },
    updatedAt: {
      type: "string",
      columnType: "datetime",
      columnName: 'updated_at',
      required: true
    },
    setting: {
      type: "string",
      columnType: "longtext",
      required: true
    },
    im_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    im_address: {
      type: "string",
      columnType: "varchar",
      maxLength: 255
    },
    im_status: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    subscribe_status: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    first_show: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    autoplay_sec: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 5
    },
    dashboard_tip: {
      type: "string",
      columnType: "char",
      maxLength: 1,
      defaultsTo: "0"
    },
    group_tip: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    createdAt: false,
  }
};
