/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_vocabulary_to_vocabulary_tags',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    vocabulary_tag_id: {
      model: "VocabularyTags"
    },
    user_vocabulary_id: {
      model: 'UserVocabulary'
    },
    studied: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    updatedAt: false
  }
};
