/**
	Generated by sails-inverse-model
	Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
*/

module.exports = {
  tableName: 'users',
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    username: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      unique: true,
      required: true
    },
    password: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      required: true
    },
    email: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      unique: true,
      required: true
    },
    code: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    name: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      required: true
    },
    ip_address: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    age_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true
    },
    country: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 64
    },
    nationality: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 64
    },
    city: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 32
    },
    avatar_url: {
      type: 'string',
      columnType: 'text'
    },
    interests: {
      type: 'string',
      columnType: 'text'
    },
    http_referer: {
      type: 'string',
      columnType: 'text'
    },
    source_type: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    },
    msn: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 64
    },
    skyper: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 64
    },
    sex: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 10
    },
    admin_note: {
      type: 'string',
      columnType: 'text'
    },
    createdAt: {
      type: 'string',
      columnType: 'datetime',
      columnName: 'created_at',
      autoCreatedAt: true
    },
    updatedAt: {
      type: 'string',
      columnType: 'datetime',
      columnName: 'updated_at',
      autoUpdatedAt: true
    },
    created_by: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 888
    },
    updated_by: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 888
    },
    birthday: {
      type: 'string',
      columnType: 'datetime'
    },
    mailing_address1: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mailing_address2: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mailing_city: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mailing_state: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mailing_country: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mailing_postal_code: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    mobile_phone: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    credit_amount: {
      type: 'number',
      columnType: 'decimal',
      defaultsTo: 0.00
    },
    ip_country: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    ip_region: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    ip_city: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    profession: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255
    },
    come: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      defaultsTo: 'site'
    },
    role_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 1
    },
    school_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 1
    },
    native: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    },
    purchase_status: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    },
    signin_source: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    },
    confirm_status: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 1
    },
    member_id: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 50
    },
    ltv: {
      type: 'number',
      columnType: 'decimal',
      defaultsTo: 0.00
    },
    ltsm: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 0
    }
  }
};
