/**
	Generated by sails-inverse-model
	Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
*/

module.exports = {
  tableName: 'user_options',
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    user_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      required: true
    },
    option_key: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      required: true
    },
    option_value: {
      type: 'string',
      columnType: 'text',
      required: true
    },
    updatedAt: {
      type: 'string',
      columnType: 'timestamp',
      columnName: 'last_update',
      autoUpdatedAt: true
    }
  }
};
