/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_contents',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    v3_id: {
      type: "string",
      columnType: "varchar",
      maxLength: 20,
      required: true
    },
    user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    status: {
      type: "string",
      columnType: "enum",
      isIn: ["active", "subscribed", "bookmarked", " assigned", "studied", "unstudied", "removed"]
    },
    source: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    label_id: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
      required: true
    },
    createdAt: {
      type: "string",
      columnType: "timestamp",
      columnName: 'created_at',
      defaultsTo: "CURRENT_TIMESTAMP"
    },
    scheduled_date: {
      type: "string",
      columnType: "date",
      required: true
    },
    content_sort: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    expiry: {
      type: "string",
      columnType: "datetime"
    },
    lesson_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    access_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    saved: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    studied: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    updatedAt: false
  }
};
