/**
 Generated by sails-inverse-model
 Date:Mon Sep 30 2019 12:48:33 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_custom_assessments',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      autoIncrement: true,
    },
    user_id: {
      // model: 'user'
      //TODO prepare this for production use
      type: "number",
      columnType: "int",
      isInteger: true,
    },
    assessment_id: {
      type: 'string',
      allowNull: true
    },
    lesson_id: {
      model: 'lessonData'
    },
    total_score: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    user_score: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    createdAt: {
      type: "ref",
      columnType: "datetime",
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnType: "datetime",
      autoUpdatedAt: true
    },
  }
};
