/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_site_links',
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      autoIncrement: true
    },
    user_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      required: true
    },
    site_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 2,
      allowNull: true
    },
    org_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    usertype_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 7,
      allowNull: true
    },
    expiry: {
      type: 'ref',
      columnType: 'datetime',
      defaultsTo: new Date().toISOString(),
    },
    active: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    deactive: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    academic_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    activity_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    other_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    show_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    newsletter_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    meetup_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    motivation_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      allowNull: true
    },
    source_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      allowNull: true
    },
    bio: {
      type: 'string',
      columnType: 'text',
      allowNull: true
    },
    is_public: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    is_display_online: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    allow_comment: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 1,
      allowNull: true
    },
    updated_by: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 888,
      allowNull: true
    },
    updatedAt: {
      type: 'ref',
      columnType: 'datetime',
      columnName: 'updated_at',
      autoUpdatedAt: true
    },
    forward_message: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    level_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    account_note: {
      type: 'string',
      columnType: 'text',
      allowNull: true
    },
    teacher_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    analysis_time: {
      type: 'ref',
      columnType: 'datetime'
    },
    status: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      allowNull: true
    },
    createdAt: {
      type: 'ref',
      columnType: 'datetime',
      columnName: 'created_at',
      autoCreatedAt: true
    },
    is_arb: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    subscription_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      allowNull: true
    },
    cc_expiry: {
      type: 'ref',
      columnType: 'datetime'
    },
    arb_start_date: {
      type: 'ref',
      columnType: 'datetime'
    },
    pp_profile_id: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      allowNull: true
    },
    segment_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      allowNull: true
    },
    is_manual: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    is_priority: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    segment_date: {
      type: 'ref',
      columnType: 'datetime'
    },
    segment_updated_at: {
      type: 'ref',
      columnType: 'datetime'
    },
    priority_info: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      allowNull: true
    },
    staff_type: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    is_on_team: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    overlay_email: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    signup_device: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    signup_user_agent: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      allowNull: true
    },
    org_group_id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      defaultsTo: 0,
      allowNull: true
    },
    custom_id: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 255,
      allowNull: true
    }
  }
};
