/**
 Generated by sails-inverse-model
 Date:Mon Sep 30 2019 12:48:33 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  datastore: 'assessment',
  tableName: 'user_assessments',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    user_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    assessment_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    lesson_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    assessment_name: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      required: true
    },
    total_score: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    user_score: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    template: {
      type: "string",
      columnType: "varchar",
      maxLength: 20,
      required: true
    },
    created_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    createdAt: {
      type: "ref",
      columnName: 'created_at',
      columnType: "datetime",
      required: true
    },
    updatedAt: false
  }
};
