/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_courses',
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'user_course_id',
      isInteger: true,
      autoIncrement: true
    },
    user_id: {
      model: 'User'
    },
    course: {
      columnName: 'course_id',
      model: 'CourseDetail'
    },
    course_title: {
      type: "string",
      columnType: "varchar",
      maxLength: 150,
      allowNull: true
    },
    default_status: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    createdAt: {
      type: "ref",
      columnType: "datetime",
      columnName: 'date_created',
      autoCreatedAt: true
    },
    created_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      columnName: 'last_modified',
      autoUpdatedAt: true
    },
    modified_by: {
      type: "number",
      columnType: "int",
      isInteger: true,
      allowNull: true
    },
    course_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    is_private: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    }
  }
};
