/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_preferences',

  customToJSON: function() {
    return _.pick(this, ['id', 'last_login', 'avatar_url'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      columnName: 'user_id',
      isInteger: true,
      required: true
    },
    login_times: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    last_login: {
      type: "ref",
      columnType: "datetime",
      defaultsTo: new Date().toISOString(),
    },
    hash_feed_only: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    data: {
      type: "string",
      columnType: "longtext",
      defaultsTo: ''
    },
    new_messages: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    teacher_email: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    user_goal: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    createdAt: {
      type: "ref",
      columnName: 'created_at',
      columnType: "timestamp",
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnName: 'updated_at',
      columnType: "datetime",
      autoUpdatedAt: true
    },
    privilege: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    dashboard_order: {
      type: "string",
      columnType: "varchar",
      maxLength: 10,
      defaultsTo: "oldest"
    },
    last_login_ip: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      required: true
    },
    avatar_url: {
      type: "string",
      columnType: "varchar",
      maxLength: 200,
      required: true
    },
    group_added: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    timezone: {
      type: "string",
      columnType: "varchar",
      maxLength: 100,
      allowNull: true
    },
    verify_code: {
      type: "string",
      columnType: "varchar",
      maxLength: 40,
      allowNull: true
    },
    school_id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 1
    },
    version_number: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    native: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
  }
};
