/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  attributes: {
    id: {
      type: 'number',
      columnType: 'int',
      isInteger: true,
      required: true
    },
    name: {
      type: 'string',
      columnType: 'varchar',
      maxLength: 20,
      unique: true,
      required: true
    },
    position: {
      type: 'number',
      columnType: 'int',
      isInteger: true
    },
    is_class: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    },
    is_teacher: {
      type: 'number',
      columnType: 'tinyint',
      isInteger: true,
      defaultsTo: 0
    }
  }
};
