/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_contents',
  customToJSON: function() {
    // Return a shallow copy of this record with the password and ssn removed.
    return _.pick(this, ['updatedAt', 'saved', 'studied', 'lesson'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    lesson: {
      model: 'LessonData',
      columnName: 'v3_id'
    },
    user_id: {
      model: 'User'
    },
    status: {
      type: "string",
      columnType: "enum",
      isIn: ["active", "subscribed", "bookmarked", " assigned", "studied", "unstudied", "removed"]
    },
    source: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 1
    },
    label_id: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
      required: true
    },
    updatedAt: {
      type: "ref",
      columnType: "timestamp",
      // columnName: 'user_contents.created_at',
      columnName: 'created_at',
      autoUpdatedAt: true
    },
    scheduled_date: {
      type: "ref",
      columnType: "date",
      required: true
    },
    content_sort: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    expiry: {
      type: "ref",
      columnType: "datetime"
    },
    lesson_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    access_type: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    saved: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    studied: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    createdAt: false,
  }
};
