/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'user_vocabulary',
  customToJSON: function() {
    return _.pick(this, ['id', 'vocabulary_id', 'visible', 'char_learned', 'correct_streak', 'number_correct', 'times_tested', 'updatedAt', 'studied'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "int",
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    user_id: {
      model: 'User'
    },
    vocabulary_id: {
      model: 'VocabularyNew'
    },
    visible: {
      type: "string",
      columnType: "enum",
      isIn: ["yes", "no"],
      defaultsTo: 'yes'
    },
    char_learned: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    correct_streak: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    number_correct: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    times_tested: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 0
    },
    last_test_date: {
      type: 'ref'
    },
    last_correct_date: {
      type: "ref"
    },
    createdAt: {
      type: "ref",
      columnName: 'created_at',
      autoCreatedAt: true
    },
    updatedAt: {
      type: "ref",
      columnName: 'updated_at',
      autoUpdatedAt: true
    },
    studied: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    }
  }
};
