/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'vocabulary_tags',
  customToJSON: function() {
    return _.pick(this, ['id', 'tag', 'public'])
  },
  attributes: {
    id: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
      unique: true,
      autoIncrement: true
    },
    tag: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    user_id: {
      model: 'User'
    },
    public: {
      type: "number",
      columnType: "tinyint",
      isInteger: true,
      defaultsTo: 0
    },
    updatedAt: false
  }
};
