/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  tableName: 'vocabulary',
  beforeDestroy: (criteria, cb) => {
    if (criteria && criteria.where && criteria.where.and) {
      let target = criteria.where.and.filter(params => params.vocabulary_class);
      if (target[0].vocabulary_class === 'User Vocabulary') {
        return cb();
      }
    }
    // sails.hooks.bugsnag.notify(`Deleting Vocabulary - ${JSON.stringify(criteria)}`);
    return cb(new Error('This is a read-only model'));
  },
  attributes: {
    id: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
      autoIncrement: true
    },
    vocabulary_class: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    s: {
      type: "string",
      columnName: 'column_1',
      columnType: "varchar",
      maxLength: 255,
      allowNull: true
    },
    p: {
      type: "string",
      columnName: 'column_2',
      columnType: "text",
      allowNull: true
    },
    en: {
      type: "string",
      columnName: 'column_3',
      columnType: "text",
      allowNull: true
    },
    t: {
      type: "string",
      columnName: 'column_4',
      columnType: "text",
      allowNull: true
    },
    audio: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    v3_id: {
      model: 'LessonData'
    },
    display_order: {
      type: "number",
      columnType: "int",
      isInteger: true,
      defaultsTo: 1
    },
    image: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    updatedAt: false,
    createdAt: false
  }
};
