/**
 Generated by sails-inverse-model
 Date:Fri May 17 2019 18:41:35 GMT+0800 (Hong Kong Standard Time)
 */

module.exports = {
  attributes: {
    id: {
      type: "number",
      columnType: "bigint",
      isInteger: true,
      autoIncrement: true
    },
    vocabulary_class: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    column_1: {
      type: "string",
      columnType: "varchar",
      maxLength: 255,
      required: true
    },
    column_2: {
      type: "string",
      columnType: "text",
      required: true
    },
    column_3: {
      type: "string",
      columnType: "text",
      required: true
    },
    column_4: {
      type: "string",
      columnType: "text",
      required: true
    },
    audio: {
      type: "string",
      columnType: "text",
      required: true
    },
    v3_id: {
      model: 'LessonData'
    },
    display_order: {
      type: "number",
      columnType: "int",
      isInteger: true,
      required: true
    },
    image: {
      type: "string",
      columnType: "text",
      allowNull: true
    },
    updatedAt: false,
    createdAt: false
  }
};
